--- pyproject.toml.orig	2024-11-06 00:31:38 UTC
+++ pyproject.toml
@@ -3,9 +3,6 @@ requires = [
 	"setuptools",
 	"wheel",
 	"setuptools_scm",
-	"scikit-build",
-	"cmake",
-	"ninja"
 ]
 build-backend = "setuptools.build_meta"
 
