--- Cargo.toml.orig	2025-02-27 08:00:33 UTC
+++ Cargo.toml
@@ -28,9 +28,7 @@ homepage = "https://fishshell.com"
 readme = "README.rst"
 
 [dependencies]
-pcre2 = { git = "https://github.com/fish-shell/rust-pcre2", tag = "0.2.9-utf32", default-features = false, features = [
-    "utf32",
-] }
+pcre2 = { path = "../rust-pcre2-0.2.9-utf32", default-features = false, features = ["utf32"] }
 
 bitflags = "2.5.0"
 errno = "0.3.0"
