--- pyproject.toml.orig	2024-11-28 08:45:25 UTC
+++ pyproject.toml
@@ -3,7 +3,7 @@
 # https://github.com/zopefoundation/meta/tree/master/config/c-code
 
 [build-system]
-requires = ["setuptools < 74"]
+requires = ["setuptools < 84"]
 build-backend = "setuptools.build_meta"
 
 [tool.coverage.run]
